# Generated by Django 2.0.2 on 2018-02-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0003_auto_20180223_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appcustomer',
            name='basket',
        ),
        migrations.RemoveField(
            model_name='order',
            name='basket',
        ),
        migrations.AddField(
            model_name='basketitem',
            name='belong_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estore.AppCustomer', verbose_name='所属客户'),
        ),
        migrations.AddField(
            model_name='basketitem',
            name='belong_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estore.Order', verbose_name='所属订单'),
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.Product', verbose_name='商品'),
        ),
    ]
