# Generated by Django 2.0.2 on 2018-02-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_auto_20180223_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appcustomer',
            old_name='belong',
            new_name='shop',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpay', '未支付'), ('payed', '已支付'), ('undeliver', '等待发货'), ('deliving', '正在运送'), ('delived', '已送达'), ('confirm', '已确认')], default='unpay', max_length=32, verbose_name='订单状态'),
        ),
    ]
