# Generated by Django 2.0.2 on 2018-02-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0005_auto_20180223_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='belong',
            new_name='customer',
        ),
    ]
