# Generated by Django 2.0.2 on 2018-02-23 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0006_auto_20180223_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estore.AppMerchant', verbose_name='所属商户'),
        ),
    ]
