# Generated by Django 2.0.2 on 2018-02-23 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_shopinfo_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estore.AppMerchant', verbose_name='所属商户'),
        ),
    ]
