# Generated by Django 2.0.2 on 2018-02-23 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0008_auto_20180223_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='belong',
            new_name='shop',
        ),
    ]
