# Generated by Django 2.0.2 on 2018-02-23 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0009_auto_20180223_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='belong',
            new_name='shop',
        ),
    ]
