# Generated by Django 2.0.2 on 2018-02-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0010_auto_20180223_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='price',
            field=models.FloatField(verbose_name='成交价格'),
        ),
    ]
