# Generated by Django 2.0.2 on 2018-02-23 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0011_auto_20180223_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='out_trade_no',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='微信支付单号'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
