# Generated by Django 2.0.2 on 2018-02-24 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0012_auto_20180223_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='estore.ShopInfo', verbose_name='所属商铺'),
        ),
    ]
