# Generated by Django 2.0.2 on 2018-02-25 06:32

from django.db import migrations, models
import django.db.models.deletion
import estore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0013_auto_20180224_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=estore.fields.ManyToManyFieldWithDDW(blank=True, to='estore.ProductCategory', verbose_name='所属分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pics',
            field=models.ManyToManyField(blank=True, related_name='pics', to='estore.Picture', verbose_name='细节图片集'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_pic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estore.Picture', verbose_name='主图'),
        ),
    ]
