# Generated by Django 2.0.2 on 2018-02-25 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0014_auto_20180225_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estore.Picture', verbose_name='主图'),
        ),
    ]
