# Generated by Django 2.0.2 on 2018-02-25 08:18

from django.db import migrations
import estore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0015_auto_20180225_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=estore.fields.ImageFieldEx(upload_to='estorepics', verbose_name='图片'),
        ),
    ]
