# Generated by Django 2.0.2 on 2018-02-25 09:19

from django.db import migrations
import django.db.models.deletion
import estore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0016_auto_20180225_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_pic',
            field=estore.fields.ForeignImgField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estore.Picture', verbose_name='主图'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='icon',
            field=estore.fields.ForeignImgField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estore.Picture', verbose_name='店铺图标'),
        ),
    ]
