# Generated by Django 2.0.2 on 2018-02-25 11:20

from django.db import migrations, models
import django.db.models.deletion
import estore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0019_auto_20180225_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='pic',
            field=estore.fields.ImageFieldEx(upload_to='estorepics', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_pic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estore.Picture', verbose_name='主图'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estore.Picture', verbose_name='店铺图标'),
        ),
    ]
