# Generated by Django 2.0.2 on 2018-02-25 14:30

from django.db import migrations
import estore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0022_shopinfo_icon2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopinfo',
            name='banners',
            field=estore.fields.ManyToManyImgField(blank=True, related_name='banners', to='estore.Picture', verbose_name='广告图片'),
        ),
    ]
