# Generated by Django 2.0.2 on 2018-02-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0024_auto_20180225_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.CharField(max_length=256, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='app_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='小程序id'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='app_secret',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='小程序密钥'),
        ),
        migrations.AlterField(
            model_name='shopinfo',
            name='description',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='店铺描述'),
        ),
    ]
